### ISSUE TITLE
Bad performance. Please do not read/write each byte one by one, but in a block

### ISSUE THREAD

**Issue by sonymaster** [JulianOzelRose/TombExtract#2]
First I would like to say, that you did a great job. The editor is very useful utility.

I have noticed that the performance when extracting and moving savegames is very poor.
I saw in the code that you read and write each byte individually in a loop.

You can use the read and write methods, to read/write the whole byte array in one step. Currently, you open, seek and close the file for each byte. This is very slow. I have tested it and can provide my findings if you need.

**Comment by JulianOzelRose** [comment]
Hello, and thank you. I had a lot of fun reversing the savegames and writing the editor.

Admittedly, I'm not too proud of this program's code... it's a bit scrappy for my taste. I was kind of writing it along as I figured out the conversion formulas for the different platforms. Anyway, give this build a try:

[TombExtract-Refactored-ReadWrite.zip](https://github.com/JulianOzelRose/TombExtract/files/14828549/TombExtract-Refactored-ReadWrite.zip)

I refactored the transfer/deletion/reordering code so that it uses just 1 or 2 file stream blocks. For reordering and deleting it just uses 1, as it's operating on the same file. For transferring it uses 2 blocks, as there's 2 different files. Should be much quicker now. With the previous implementation it took ~2 minutes to transfer 32 savegames. With this refactored code, it takes about 5 seconds.

Note that I haven't implemented the conversion code yet for this version, so it will only transfer savegames as is. Let me know how it works for you and if everything is good I will update the repo :)

EDIT:  [This build](https://github.com/JulianOzelRose/TombExtract/files/14831354/TombExtract-Refactored-ReadWrite-Reorder.zip) has the refactor for savegame reordering

**Comment by sonymaster** [comment]
It works perfect. Many thanks for the quick implementation. Now it moves/deletes/transfers the savegames in seconds. Previously it took 2 minutes per savegame (modern PC with SSD).

**Comment by JulianOzelRose** [comment]
No problem, glad it works well.

I'm off to bed, so I'll update the repo tomorrow. If you'd like, I can credit you in the release notes for the read/write performance tips.

**Comment by sonymaster** [comment]
My contribution was so small that I don't insist ;-). You decide.
